use crate::exchange::constants::{
    MarketType, MARKET_FLAG_BEIJING, MARKET_FLAG_HONG_KONG, MARKET_FLAG_SHANGHAI,
    MARKET_FLAG_SHENZHEN, MARKET_FLAG_USA, MARKET_ID_BEIJING, MARKET_ID_HONG_KONG,
    MARKET_ID_SHANGHAI, MARKET_ID_SHENZHEN, MARKET_ID_USA,
};

pub fn get_market_flag(market_id: MarketType) -> &'static str {
    match market_id {
        MARKET_ID_SHENZHEN => MARKET_FLAG_SHENZHEN,
        MARKET_ID_BEIJING => MARKET_FLAG_BEIJING,
        MARKET_ID_HONG_KONG => MARKET_FLAG_HONG_KONG,
        MARKET_ID_USA => MARKET_FLAG_USA,
        MARKET_ID_SHANGHAI => MARKET_FLAG_SHANGHAI,
        _ => MARKET_FLAG_SHANGHAI,
    }
}
